<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Authors>Microsoft, Eric White, Lionel Vallet, Mitchell Kutchuk</Authors>
		<RepositoryUrl>https://github.com/royal-road/Open-Xml-PowerTools</RepositoryUrl>
		<PackageId>RoyalRoad.OpenXmlPowerTools</PackageId>
		<PackageTags>OpenXmlPowerTools, NET, Standard, OpenXML, Power, Tools</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/royal-road/Open-Xml-PowerTools</PackageProjectUrl>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Description>
			Based on maintainer EricWhite's vNext fork, includes .NET 8.0, .NET 9.0, .NET 10.0 and .NET Standard 2.0 build target for use in cross-platform scenarios.

			The Open XML PowerTools provides guidance and example code for programming with Open XML Documents (DOCX, XLSX, and PPTX). It is based on, and extends the functionality of the Open XML SDK.

			It supports scenarios such as:
			•Splitting DOCX/PPTX files into multiple files.
		•Combining multiple DOCX/PPTX files into a single file.
			•Populating content in template DOCX files with data from XML.
			•High-fidelity conversion of DOCX to HTML.
			•Searching and replacing content in DOCX/PPTX using regular expressions.
			•Managing tracked-revisions, including detecting tracked revisions, and accepting tracked revisions.
			•Updating Charts in DOCX/PPTX files, including updating cached data, as well as the embedded XLSX.
			•Retrieving metrics from DOCX files, including the hierarchy of styles used, the languages used, and the fonts used.
			•Writing XLSX files using far simpler code than directly writing the markup, including a streaming approach that enables writing XLSX files with millions of rows.
		</Description>
		<Version>4.7.1</Version>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>
	<ItemGroup>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DocumentFormat.OpenXml" Version="2.14.0" />
		<PackageReference Include="SkiaSharp" Version="3.116.1" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Update="StyleCop.Analyzers" Version="1.1.118" />
	</ItemGroup>
</Project>
