name: Publish NuGet

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x
            10.x
      - name: Build
        run: dotnet build ./OpenXmlPowerTools -c Release
      - name: Pack
        run: dotnet pack ./OpenXmlPowerTools -c Release -o ./out
      - name: Push to NuGet.org
        run: dotnet nuget push ./out/*.nupkg -k ${{secrets.NUGET_API_KEY}} -s https://api.nuget.org/v3/index.json
